Prevent dashboard crashing when 0 messages in room
This would cause us to try to make the `progressBarJuice` with `Infinity` long repeat:

```
RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at /opt/gitter/gitter-webapp-staging/scripts/utils/gitter-to-matrix-historical-import-worker-dashboard.js:71:34
    ...
```