Small fixes to the Matrix backfilling history script pt. 7
 - Make performance marks unique so we don't mix them together when measuring
 - Prevent dashboard crashing when 0 messages in room. This would cause us to try to make the `progressBarJuice` with `Infinity` long repeat:
    ```
    RangeError: Invalid count value
        at String.repeat (<anonymous>)
        at /opt/gitter/gitter-webapp-staging/scripts/utils/gitter-to-matrix-historical-import-worker-dashboard.js:71:34
        ...
    ```
    - I'm confused why this doesn't happen more as I see this working many times with `0` messages in the room. Above is just my theory on why it's happening.


Follow-up to https://gitlab.com/gitterHQ/webapp/-/merge_requests/2313

Part of https://gitlab.com/gitterHQ/webapp/-/issues/2609